### PR TITLE
Add GOBIN to dev environment setup

### PR DESCRIPTION
**Pull request by Nagyman**
Avoids this issue on OSX:

`go install: no install location for directory /Users/... outside GOPATH`

### CODE REVIEW

**Comment by bartek** [comment]
@Nagyman Hm, I didn't encounter this on OSX. I can't see a reason to have to set GOBIN. Maybe @jlabath can comment further.

**Comment by jlabath** [comment]
@bartek @Nagyman I'm stumped. I literary never encountered this.

This is my setup on my mac
```
export GOPATH="/compass/gocode"
export PATH=/compass/go/bin:$GOPATH/bin:$PATH
```

That's it two variables. Same for my linux box at home.

```
export GOPATH=$HOME/gocode
export PATH=$HOME/go/bin:$GOPATH/bin:$PATH
```

I wonder if you are experiencing all of this because you are using go from homebrew/ubuntu package manager/ etc. The second some stubborn package managers start sticking binaries in /usr/bin and libraries in /usr/lib it can fall apart pretty quickly. And you may well need to set the GOROOT and GOBIN.

For ease of use I suggest to just download the tar.gz for your platform, from golang.org. And unpack it and set the PATH and GOPATH and you should be good to go.

That aside if it works - it works! The proof is in the pudding. So maybe the guide might just say - depending on your platform and how you installed go you may need to set GOROOT and GOBIN.

Cheers

**Comment by Nagyman** [comment]
I used the OSX package from the go site (no homebrew), which installed to `/usr/local/go`, but now I've got this when attempting `go get`

`go install _/Users/craign/dev/bundler/cmd/bundler: open /usr/local/go/bin/bundler: permission denied`

So I'll probably uninstall and try the plain old gzip version instead of the package. I don't need it, just futzing around trying to compile it (mostly for curiosity).

**Comment by Nagyman** [comment]
The zip works fine :P  Closing.

**Comment by jlabath** [comment]
@Nagyman I see. So the bundler (or majortom) are not actually go installable. This is because they are private repositories. Where go get assumes public access. They still live within respective paths - within GOPATH. E.g. `import "github.com/gadventures/bundler"` expects to find the bundler under $GOPATH/src/github.com/gadventures/bundler. I just noticed we don't have this in the README. Just ping me for more details as you are going throught it. Sorry for lack of docs.

```
(go) jakub@fedor ~/gocode/src/github.com/gadventures $ echo $GOPATH
/home/jakub/gocode
(go) jakub@fedor ~/gocode/src/github.com/gadventures $ pwd
/home/jakub/gocode/src/github.com/gadventures
(go) jakub@fedor ~/gocode/src/github.com/gadventures $ git clone git@github.com:gadventures/bundler.git
```

**Pull request closed without merging**
